### PR TITLE
Update runner-ex4.yml

### PR DESCRIPTION
**Pull request by eyaly**
From Thiago:
the concept behind the 2 different ways of selecting a device are:
dynamic: you can use a regex to match multiple devices (useful for when the customer wants, for example, ANY iPhone X: name: iPhone X)
hardcoded (static): you can only match a single device with the exact ID it has (useful for when the customer wants a really specific device: id: iPhone_X_us_real1 , commonly used by customers with private devices)

@wswebcreation - can you review and merge?

### CODE REVIEW

**Review by wswebcreation — COMMENTED** [review]
@eyal,

`name` still works, this is "how" the TO version worked. What's the reason for using this with `id`?

Secondly, if we need to change it to `id` maybe add a comment in all files that use static allocation, and also create a PR for XCUITest, because it's also used there

Thanks

**Comment by eyaly** [comment]
@wswebcreation - You wrote:
also create a PR for XCUITest, because it's also used there.
Can you share the repo? 
I found this repo:
https://github.com/saucelabs/saucectl-xcuitest-example/blob/main/.sauce/config.yml
and the code is:
devices:     
 # If set, only device by ID will be queried.   
#- id: &lt;rdc_device_id&gt;     
- name: "iPhone.*"

But with the espresso demo, it is really not clear. They added the 2 parameters...
https://github.com/saucelabs/saucectl-espresso-example/blob/master/.sauce/config.yml

**Comment by wswebcreation** [comment]
https://github.com/saucelabs-training/demo-xcuitest

**Comment by wswebcreation** [comment]
As discussed closing this one

**Pull request closed without merging**
